prompt --application/pages/page_00004
begin
--   Manifest
--     PAGE: 00004
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.04.15'
,p_release=>'21.1.6'
,p_default_workspace_id=>9869175406039007
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'APEX_APP'
);
wwv_flow_api.create_page(
 p_id=>4
,p_user_interface_id=>wwv_flow_api.id(11033376187154093)
,p_name=>unistr('Grupy u\017Cytkownik\00F3w')
,p_alias=>unistr('GRUPY-U\017BYTKOWNIK\00D3W')
,p_step_title=>unistr('Grupy u\017Cytkownik\00F3w')
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'ADMIN'
,p_last_upd_yyyymmddhh24miss=>'20211230134908'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(19230758257656107)
,p_plug_name=>unistr('Grupy u\017Cytkownik\00F3w')
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(10770462220153784)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_api.id(10703479224153541)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_api.id(10827598609153899)
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(19230840772656108)
,p_plug_name=>unistr('Grupy pracownik\00F3w')
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(10759184148153770)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT ID,',
'       NAZWA,',
'       AKTYWNE,',
'       DATA_UTWORZENIA,',
'       PRACOWNIK_TWORZACY',
'  FROM ADMIN.GRUPY_PRACOWNIKOW t',
' WHERE (:P4_NAZWA_GRUPY IS NULL OR upper(nazwa) LIKE upper(''%'' || :P4_NAZWA_GRUPY || ''%''))',
'   AND (:P4_PRACOWNIK_TWORZACY IS NULL OR pracownik_tworzacy = :P4_PRACOWNIK_TWORZACY)',
'   AND (:P4_DATA_UTWORZENIA_OD IS NULL OR data_utworzenia >= :P4_DATA_UTWORZENIA_OD)',
'   AND (:P4_DATA_UTWORZENIA_DO IS NULL OR data_utworzenia >= :P4_DATA_UTWORZENIA_DO)',
'   AND ((:P4_TYLKO_AKTYWNE = ''T'' AND aktywne = ''T'') OR :P4_TYLKO_AKTYWNE = ''N'')',
'   AND (:P4_PRACOWNIK_W_GRUPIE IS NULL OR EXISTS (SELECT 1 FROM admin.szczegoly_grup_pracownikow WHERE pracownik = :P4_PRACOWNIK_W_GRUPIE AND grupa_pracownikow = t.id))'))
,p_plug_source_type=>'NATIVE_IG'
,p_ajax_items_to_submit=>'P4_NAZWA_GRUPY,P4_PRACOWNIK_TWORZACY,P4_PRACOWNIK_W_GRUPIE,P4_DATA_UTWORZENIA_OD,P4_TYLKO_AKTYWNE,P4_DATA_UTWORZENIA_DO'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_prn_units=>'MILLIMETERS'
,p_prn_paper_size=>'A4'
,p_prn_width=>297
,p_prn_height=>210
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>unistr('Grupy pracownik\00F3w')
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(19231083826656110)
,p_name=>'ID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ID'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_LINK'
,p_heading=>'ID'
,p_heading_alignment=>'CENTER'
,p_display_sequence=>10
,p_value_alignment=>'LEFT'
,p_link_target=>'f?p=&APP_ID.:6:&SESSION.::&DEBUG.::P6_ID:&ID.'
,p_link_text=>'&ID.'
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
,p_escape_on_http_output=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(19231120914656111)
,p_name=>'NAZWA'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'NAZWA'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Nazwa grupy'
,p_heading_alignment=>'CENTER'
,p_display_sequence=>20
,p_value_alignment=>'LEFT'
,p_attribute_05=>'BOTH'
,p_is_required=>true
,p_max_length=>30
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(19231252202656112)
,p_name=>'AKTYWNE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'AKTYWNE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_SINGLE_CHECKBOX'
,p_heading=>'Aktywna'
,p_heading_alignment=>'CENTER'
,p_display_sequence=>30
,p_value_alignment=>'LEFT'
,p_attribute_01=>'N'
,p_attribute_02=>'T'
,p_attribute_03=>'N'
,p_is_required=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(19231397130656113)
,p_name=>'DATA_UTWORZENIA'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DATA_UTWORZENIA'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_DATE_PICKER_JET'
,p_heading=>'Data utworzenia'
,p_heading_alignment=>'CENTER'
,p_display_sequence=>40
,p_value_alignment=>'LEFT'
,p_attribute_01=>'N'
,p_attribute_02=>'POPUP'
,p_attribute_03=>'NONE'
,p_attribute_06=>'NONE'
,p_attribute_09=>'N'
,p_attribute_11=>'Y'
,p_format_mask=>'DD.MM.YYYY'
,p_is_required=>true
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_date_ranges=>'ALL'
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(19231417503656114)
,p_name=>'PRACOWNIK_TWORZACY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'PRACOWNIK_TWORZACY'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_SELECT_LIST'
,p_heading=>unistr('Pracownik tworz\0105cy')
,p_heading_alignment=>'CENTER'
,p_display_sequence=>50
,p_value_alignment=>'LEFT'
,p_is_required=>true
,p_lov_type=>'SHARED'
,p_lov_id=>wwv_flow_api.id(19245212945766405)
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'LOV'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_interactive_grid(
 p_id=>wwv_flow_api.id(19230977114656109)
,p_internal_uid=>19230977114656109
,p_is_editable=>false
,p_lazy_loading=>true
,p_requires_filter=>false
,p_select_first_row=>true
,p_fixed_row_height=>true
,p_pagination_type=>'SCROLL'
,p_show_total_row_count=>true
,p_show_toolbar=>true
,p_toolbar_buttons=>'ACTIONS_MENU:RESET:SAVE'
,p_enable_save_public_report=>false
,p_enable_subscriptions=>true
,p_enable_flashback=>true
,p_define_chart_view=>true
,p_enable_download=>true
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>true
,p_fixed_header=>'PAGE'
,p_show_icon_view=>false
,p_show_detail_view=>false
);
wwv_flow_api.create_ig_report(
 p_id=>wwv_flow_api.id(19247794956963512)
,p_interactive_grid_id=>wwv_flow_api.id(19230977114656109)
,p_static_id=>'192478'
,p_type=>'PRIMARY'
,p_default_view=>'GRID'
,p_show_row_number=>false
,p_settings_area_expanded=>true
);
wwv_flow_api.create_ig_report_view(
 p_id=>wwv_flow_api.id(19247981915963514)
,p_report_id=>wwv_flow_api.id(19247794956963512)
,p_view_type=>'GRID'
,p_srv_exclude_null_values=>false
,p_srv_only_display_columns=>true
,p_edit_mode=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(19248423949963522)
,p_view_id=>wwv_flow_api.id(19247981915963514)
,p_display_seq=>1
,p_column_id=>wwv_flow_api.id(19231083826656110)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(19249366353963531)
,p_view_id=>wwv_flow_api.id(19247981915963514)
,p_display_seq=>2
,p_column_id=>wwv_flow_api.id(19231120914656111)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(19250243367963537)
,p_view_id=>wwv_flow_api.id(19247981915963514)
,p_display_seq=>3
,p_column_id=>wwv_flow_api.id(19231252202656112)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(19251105469963541)
,p_view_id=>wwv_flow_api.id(19247981915963514)
,p_display_seq=>4
,p_column_id=>wwv_flow_api.id(19231397130656113)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(19252075432963546)
,p_view_id=>wwv_flow_api.id(19247981915963514)
,p_display_seq=>5
,p_column_id=>wwv_flow_api.id(19231417503656114)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(19232236020656122)
,p_plug_name=>'Filtrowanie'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_api.id(10761094506153773)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(19232947789656129)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_api.id(19232236020656122)
,p_button_name=>'Filtruj'
,p_button_action=>'DEFINED_BY_DA'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(10826139852153896)
,p_button_image_alt=>'Filtruj'
,p_button_position=>'REGION_TEMPLATE_CREATE'
,p_warn_on_unsaved_changes=>null
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(19232339494656123)
,p_name=>'P4_NAZWA_GRUPY'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_api.id(19232236020656122)
,p_prompt=>'Nazwa grupy'
,p_post_element_text=>'"CLEAR_BUTTON_OPTIONAL"'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>36
,p_tag_attributes=>'style="width:230px"'
,p_field_template=>wwv_flow_api.id(10823453913153885)
,p_item_template_options=>'#DEFAULT#'
,p_attribute_01=>'N'
,p_attribute_02=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(19232450091656124)
,p_name=>'P4_TYLKO_AKTYWNE'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_api.id(19232236020656122)
,p_prompt=>'Tylko aktywne'
,p_display_as=>'NATIVE_SINGLE_CHECKBOX'
,p_tag_attributes=>'style="width:200px"'
,p_begin_on_new_line=>'N'
,p_field_template=>wwv_flow_api.id(10823453913153885)
,p_item_template_options=>'#DEFAULT#'
,p_attribute_01=>'N'
,p_attribute_02=>'T'
,p_attribute_03=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(19232530566656125)
,p_name=>'P4_PRACOWNIK_W_GRUPIE'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_api.id(19232236020656122)
,p_prompt=>'Pracownik w grupie'
,p_post_element_text=>'"CLEAR_BUTTON_OPTIONAL"'
,p_display_as=>'NATIVE_POPUP_LOV'
,p_named_lov=>'LOV_PRACOWNICY'
,p_lov_display_null=>'YES'
,p_cSize=>30
,p_tag_attributes=>'style="width:170px"'
,p_begin_on_new_line=>'N'
,p_field_template=>wwv_flow_api.id(10823453913153885)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_attribute_01=>'POPUP'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_03=>'N'
,p_attribute_04=>'N'
,p_attribute_05=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(19232627067656126)
,p_name=>'P4_PRACOWNIK_TWORZACY'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(19232236020656122)
,p_prompt=>'Pracownik tworzacy'
,p_post_element_text=>'"CLEAR_BUTTON_OPTIONAL"'
,p_display_as=>'NATIVE_POPUP_LOV'
,p_named_lov=>'LOV_PRACOWNICY'
,p_lov_display_null=>'YES'
,p_cSize=>30
,p_tag_attributes=>'style="width:200px"'
,p_begin_on_new_line=>'N'
,p_begin_on_new_field=>'N'
,p_field_template=>wwv_flow_api.id(10823453913153885)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_attribute_01=>'POPUP'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_03=>'N'
,p_attribute_04=>'N'
,p_attribute_05=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(19232769928656127)
,p_name=>'P4_DATA_UTWORZENIA_OD'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_api.id(19232236020656122)
,p_prompt=>'Data utworzenia od'
,p_post_element_text=>'"CLEAR_BUTTON_OPTIONAL"'
,p_display_as=>'NATIVE_DATE_PICKER_JET'
,p_cSize=>30
,p_tag_attributes=>'style="width:200px"'
,p_begin_on_new_line=>'N'
,p_begin_on_new_field=>'N'
,p_field_template=>wwv_flow_api.id(10823453913153885)
,p_item_template_options=>'#DEFAULT#'
,p_attribute_01=>'N'
,p_attribute_02=>'POPUP'
,p_attribute_03=>'NONE'
,p_attribute_06=>'NONE'
,p_attribute_09=>'N'
,p_attribute_11=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(19232857913656128)
,p_name=>'P4_DATA_UTWORZENIA_DO'
,p_item_sequence=>70
,p_item_plug_id=>wwv_flow_api.id(19232236020656122)
,p_prompt=>'Data utworzenia do'
,p_post_element_text=>'"CLEAR_BUTTON_OPTIONAL"'
,p_display_as=>'NATIVE_DATE_PICKER_JET'
,p_cSize=>30
,p_tag_attributes=>'style="width:200px"'
,p_begin_on_new_line=>'N'
,p_begin_on_new_field=>'N'
,p_field_template=>wwv_flow_api.id(10823453913153885)
,p_item_template_options=>'#DEFAULT#'
,p_attribute_01=>'N'
,p_attribute_02=>'POPUP'
,p_attribute_03=>'NONE'
,p_attribute_06=>'NONE'
,p_attribute_09=>'N'
,p_attribute_11=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(19231505305656115)
,p_name=>'Przyciski'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(19231671168656116)
,p_event_id=>wwv_flow_api.id(19231505305656115)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'PLUGIN_COM.FOS.INTERACTIVE_GRID_ADD_BUTTON'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19230840772656108)
,p_attribute_01=>'toolbar-actions3'
,p_attribute_02=>'last'
,p_attribute_05=>'Nowa grupa'
,p_attribute_06=>'fa-plus'
,p_attribute_09=>'trigger-event'
,p_attribute_12=>'nowa_grupa'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(19231754624656117)
,p_name=>'nowa_grupa'
,p_event_sequence=>20
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_api.id(19230840772656108)
,p_bind_type=>'bind'
,p_bind_event_type=>'custom'
,p_bind_event_type_custom=>'nowa_grupa'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(19231806460656118)
,p_event_id=>wwv_flow_api.id(19231754624656117)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'PLUGIN_COM.FOS.REDIRECT'
,p_attribute_01=>'static'
,p_attribute_02=>'f?p=&APP_ID.:5:&SESSION.::&DEBUG.:::'
,p_attribute_09=>'Y'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(19292195206305411)
,p_name=>'Filtruj'
,p_event_sequence=>30
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_api.id(19232947789656129)
,p_bind_type=>'bind'
,p_bind_event_type=>'click'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(19292213872305412)
,p_event_id=>wwv_flow_api.id(19292195206305411)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19230840772656108)
);
wwv_flow_api.component_end;
end;
/
